version: 2.1

jobs:
  build:
    working_directory: ~/src
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: "install requirements and run bot"
          command:  |
            pip install -r requirements.txt
            python src/bot.py
  test:
    working_directory: ~/src
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: python src/test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
